-- AlterTable
ALTER TABLE "ProductInventory" ALTER COLUMN "reserve1" SET DEFAULT 'USE ME LATER',
ALTER COLUMN "reserve2" SET DEFAULT 'USE ME LATER',
ALTER COLUMN "reserve3" SET DEFAULT 'USE ME LATER';
